image: docker:latest

stages:
  - build

services:
  - docker:dind

before_script:
  - docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD" $DOCKER_REGISTRY

docker:build:only-main:prometheus:
  stage: build
  script:
    - docker build -t index.docker.io/mbasri/prometheus:latest docker/prometheus
    - docker tag index.docker.io/mbasri/prometheus:latest index.docker.io/mbasri/prometheus:${CI_COMMIT_SHORT_SHA}
    - docker push index.docker.io/mbasri/prometheus:latest
    - docker push index.docker.io/mbasri/prometheus:${CI_COMMIT_SHORT_SHA}
  only:
    - main

docker:build:only-main:node-exporter:
  stage: build
  script:
    - docker build -t index.docker.io/mbasri/node-exporter:latest docker/node-exporter
    - docker tag index.docker.io/mbasri/node-exporter:latest index.docker.io/mbasri/node-exporter:${CI_COMMIT_SHORT_SHA}
    - docker push index.docker.io/mbasri/node-exporter:latest
    - docker push index.docker.io/mbasri/node-exporter:${CI_COMMIT_SHORT_SHA}
  only:
    - main

docker:build:except-main:prometheus:
  stage: build
  script:
    - docker build -t index.docker.io/mbasri/prometheus:${CI_COMMIT_SHORT_SHA} docker/prometheus
    - docker push index.docker.io/mbasri/prometheus:${CI_COMMIT_SHORT_SHA}
  except:
    - main

docker:build:except-main:node-exporter:
  stage: build
  script:
    - docker build -t index.docker.io/mbasri/node-exporter:${CI_COMMIT_SHORT_SHA} docker/node-exporter
    - docker push index.docker.io/mbasri/node-exporter:${CI_COMMIT_SHORT_SHA}
  except:
    - main