FROM prom/node-exporter:v1.8.2

LABEL org.opencontainers.image.source="https://github.com/mbasri/monitoring" \
      org.opencontainers.image.description="Prometheus Node Exporter is a Prometheus exporter for hardware and OS metrics exposed by *NIX kernels, written in Go with pluggable metric collectors" \
      org.opencontainers.image.licenses="MIT"

#COPY files.d/etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 9100
