#!/usr/bin/env bash

######################################
# build
# Description: Build, tag & push a docker image to DockerHub
# Usage: ./build
# Version: 1.0
######################################

VERSION=${1:-latest}

docker login ghcr.io

for docker_image in "prometheus" "node-exporter"
do
  REPOSITORY="ghcr.io/mbasri/${docker_image}"
  if [ "${?}" -eq 0 ]; then
    docker build -t ${REPOSITORY}:${VERSION} ${docker_image}
    docker push ${REPOSITORY}:${VERSION}
    if [ "${?}" -eq 0 ]; then
      docker tag ${REPOSITORY} ${REPOSITORY}:latest
      docker push ${REPOSITORY}:latest
    fi
  else
    echo -n "Login failed, exiting"
    exit 1
  fi
done