#!/usr/bin/env bash

######################################
# build
# Description: Build, tag & push a docker image to DockerHub
# Usage: ./build
# Version: 1.0
######################################

VERSION=${1:-latest}

docker login

for docker_image in "prometheus" "node-exporter"
do
  REPOSITORY="mbasri/${docker_image}:${VERSION}"
  if [ "${?}" -eq 0 ]; then
    docker build -t ${REPOSITORY} ${docker_image}
    docker push ${REPOSITORY}
    if [ "${?}" -eq 0 ]; then
      VERSION="latest"
      REPOSITORY_LATEST="mbasri/${docker_image}:${VERSION}"
      docker tag ${REPOSITORY} ${REPOSITORY_LATEST}
      docker push ${REPOSITORY_LATEST}
    fi
  else
    echo -n "Login failed, exiting"
    exit 1
  fi
done