version: '3.8'
services:
  prometheus:
    image: mbasri/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - $PWD/files.d/prometheus:/prometheus
      - $PWD/files.d/etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped

  influxdb-backup:
    image: mbasri/node-exporter:latest
    container_name: node-exporter
    ports:
      - 9100:9100

    restart: unless-stopped
  