FROM prom/prometheus:v3.1.0

LABEL org.opencontainers.image.source="https://github.com/mbasri/monitoring" \
      org.opencontainers.image.description="Prometheus is an open-source systems monitoring and alerting toolkit" \
      org.opencontainers.image.licenses="MIT"

#COPY files.d/etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 9090
