name: 'Build, Scan & Publish Docker image'

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main, dev ]
    inputs:
      description:
        description: 'Description of the build'
        required: true
        default: ''
env:
  CONTAINER_REGISTRY: 'ghcr.io'
  LATEST_TAG: 'latest'
  PROMETHEUS_DIRECTORY: 'docker/prometheus'
  NODE_EXPORTER_DIRECTORY: 'docker/node-exporter'
  
  

jobs:
  'Build Promethus':
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: echo "Build"
    - name: Build
      run: echo ${{ github.event.inputs.description }}
