name: 'Build, Scan & Publish Docker image'

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main, dev ]
    inputs:
      enable-date-versioning:
        description: 'Enable date tag'
        required: true
        default: 'false'
        type: boolean
    # ${{ github.event.inputs.description }}
env:
  
  PROMETHEUS_DIRECTORY: 'docker/prometheus' 
  PROMETHEUS_IMAGE_NAME: 'mbasri/prometheus'

  NODE_EXPORTER_DIRECTORY: 'docker/node-exporter'
  NODE_EXPORTER_IMAGE_NAME: 'mbasri/node-exporter'
  
jobs:
  # Job to generate a version based on the current date and time
  generate-version:
    runs-on: ubuntu-latest
    name: Generate version
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
    - name: Generate date version
      id: version
      run: echo "version=$(date +'%Y%m%d%H%M%S')" >> "$GITHUB_OUTPUT"

  # Job to build the Prometheus Docker image
  build-prometheus:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write # needed for signing the images with GitHub OIDC Token

    needs: [ generate-version ]
    name: Build Prometheus image
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Build, Push and Sign Docker Image
      uses: mbasri-actions/dockerize@dev
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        docker-directory: ${{ env.PROMETHEUS_DIRECTORY }}
        image-name: ${{ env.PROMETHEUS_IMAGE_NAME }}
        tags: ${{ needs.generate-version.outputs.version }}

  scan-prometheus:
    runs-on: ubuntu-latest
    needs: [ generate-version, build-prometheus ]
    name: Scan Prometheus image
    steps:
    - uses: mbasri-actions/docker-scan@dev
      with:
        image-ref: ghcr.io/${{ env.PROMETHEUS_IMAGE_NAME }}:${{ needs.generate-version.outputs.version }}
