name: 'Build, Scan & Publish Docker image'

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main, dev ]
    # inputs:
    #   description:
    #     description: 'Description of the build'
    #     required: true
    #     default: ''
    # ${{ github.event.inputs.description }}
env:
  CONTAINER_REGISTRY: 'ghcr.io'
  
  LATEST_TAG: 'latest'
  
  PROMETHEUS_DIRECTORY: 'docker/prometheus'
  PROMETHEUS_IMAGE_NAME: 'mbasri/prometheus'

  NODE_EXPORTER_DIRECTORY: 'docker/node-exporter'
  NODE_EXPORTER_IMAGE_NAME: 'mbasri/node-exporter'
  
jobs:
  # Job to generate a version based on the current date and time
  generate-date-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
    - name: Generate date version
      id: version
      run: echo "version=$(date +'%Y%m%d%H%M%S')" >> "$GITHUB_OUTPUT"

  # Job to generate a version based on the current commit SHA
  generate-commit-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
    - name: Generate commit version
      id: version
      run: echo "version=${{ github.sha }}" >> "$GITHUB_OUTPUT"

  # Job to build the Prometheus Docker image
  build-prometheus:
    runs-on: ubuntu-latest
    needs: [ generate-date-version, generate-commit-version ]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build Prometheus Docker image
      run: |
        docker build \
          -t ${{ env.PROMETHEUS_IMAGE_NAME }}:${{ needs.generate-date-version.outputs.version }} \
          -t ${{ env.PROMETHEUS_IMAGE_NAME }}:${{ needs.generate-commit-version.outputs.version }} \
          ${{ env.PROMETHEUS_DIRECTORY }}

  # Job to scan the Prometheus Docker image
  scan-prometheus:
    runs-on: ubuntu-latest
    needs: [build-prometheus]
    steps:
    - name: Scan Prometheus Docker image
      run: echo "scan-prometheus"

  # Job to publish the Prometheus Docker image
  publish-prometheus:
    runs-on: ubuntu-latest
    needs: [scan-prometheus]
    steps:
    - name: Publish Prometheus Docker image
      run: echo "publish-prometheus"

  # Job to build the Node Exporter Docker image
  build-node-exporter:
    runs-on: ubuntu-latest
    needs: [ generate-date-version, generate-commit-version ]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build Node Exporter Docker image
      run: |
          docker build \
            -t ${{ env.NODE_EXPORTER_IMAGE_NAME }}:${{ needs.generate-date-version.outputs.version }} \
            -t ${{ env.NODE_EXPORTER_IMAGE_NAME }}:${{ needs.generate-commit-version.outputs.version }} \
            ${{ env.NODE_EXPORTER_DIRECTORY }}

  # Job to scan the Node Exporter Docker image
  scan-node-exporter:
    runs-on: ubuntu-latest
    needs: [build-node-exporter]
    steps:
    - name: Scan Node Exporter Docker image
      run: echo "scan-node-exporter"

  # Job to publish the Node Exporter Docker image
  publish-node-exporter:
    runs-on: ubuntu-latest
    needs: [scan-node-exporter]
    steps:
    - name: Publish Node Exporter Docker image
      run: echo "publish-node-exporter"
