name: 'Build, Scan & Publish Docker image'

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main, dev ]
    inputs:
      description:
        description: 'Description of the build'
        required: true
        default: ''
env:
  CONTAINER_REGISTRY: 'ghcr.io'
  
  LATEST_TAG: 'latest'
  
  PROMETHEUS_DIRECTORY: 'docker/prometheus'
  PROMETHEUS_IMAGE_NAME: 'mbasri/prometheus'

  NODE_EXPORTER_DIRECTORY: 'docker/node-exporter'
  Node_EXPORTER_IMAGE_NAME: 'mbasri/node-exporter'
  
jobs:
  generate-date-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
    - name: Generate date version
      id: version
      run: echo "version=$(date +'%Y%m%d%H%M%S')" >> "$GITHUB_OUTPUT"
  generate-commit-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
    - name: Generate commit version
      id: version
      run: echo "version=${{ github.sha }}" >> "$GITHUB_OUTPUT"

  build-prometheus:
    runs-on: ubuntu-latest
    needs: [ generate-date-version, generate-commit-version ]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build Prometheus Docker image
      run: docker build -t ${{ var.PROMETHEUS_IMAGE_NAME }}:${{ needs.generate-date-version.outputs.version }} ${{ var.PROMETHEUS_DIRECTORY }}
    #- name: Build 
    #  run: echo ${{ github.event.inputs.description }}
  scan-prometheus:
    runs-on: ubuntu-latest
    needs: [build-prometheus]
    steps:
    - name: Scan Promethues Docker image
      run: echo "scan-prometheus"
  publish-prometheus:
    runs-on: ubuntu-latest
    needs: [scan-prometheus]
    steps:
    - name: Publish Prometheus Docker image
      run: echo "publish-prometheus"

  build-node-exporter:
    runs-on: ubuntu-latest
    needs: [ generate-date-version, generate-commit-version ]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build Node Exporter Docker image
      run: echo "build-node-exporter"
  scan-node-exporter:
    runs-on: ubuntu-latest
    needs: [build-node-exporter]
    steps:
    - name: Scan Node Exporter Docker image
      run: echo "scan-node-exporter"
  publish-node-exporter:
    runs-on: ubuntu-latest
    needs: [scan-node-exporter]
    steps:
    - name: Publish Node Exporter Docker image
      run: echo "publish-node-exporter"
    
