name: 'Build, Scan & Publish Docker image'

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main, dev ]
    inputs:
      description:
        description: 'Description of the build'
        required: true
        default: ''
env:
  CONTAINER_REGISTRY: 'ghcr.io'
  LATEST_TAG: 'latest'
  PROMETHEUS_DIRECTORY: 'docker/prometheus'
  NODE_EXPORTER_DIRECTORY: 'docker/node-exporter'
  
  

jobs:
  generate-date-version:
    runs-on: ubuntu-latest
    steps:
    - name: Generate date version
      id: version
      run: echo "$(date +'%Y%m%d%H%M%S')"
  generate-commit-version:
    runs-on: ubuntu-latest
    steps:
    - name: Generate commit version
      run: echo "${github.sha}"

  build-prometheus:
    runs-on: ubuntu-latest
    needs: [ generate-date-version, generate-commit-version ]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build Prometheus Docker image
      run: docker buil
    #- name: Build 
    #  run: echo ${{ github.event.inputs.description }}
  scan-prometheus:
    runs-on: ubuntu-latest
    needs: [build-prometheus]
    steps:
    - name: Scan Promethues Docker image
      run: echo "scan-prometheus"
  publish-prometheus:
    runs-on: ubuntu-latest
    needs: [scan-prometheus]
    steps:
    - name: Publish Prometheus Docker image
      run: echo "publish-prometheus"

  build-node-exporter:
    runs-on: ubuntu-latest
    needs: [ generate-date-version, generate-commit-version ]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build Node Exporter Docker image
      run: echo "build-node-exporter"
  scan-node-exporter:
    runs-on: ubuntu-latest
    needs: [build-node-exporter]
    steps:
    - name: Scan Node Exporter Docker image
      run: echo "scan-node-exporter"
  publish-node-exporter:
    runs-on: ubuntu-latest
    needs: [scan-node-exporter]
    steps:
    - name: Publish Node Exporter Docker image
      run: echo "publish-node-exporter"
    
