name: 'Purge registry'

on:
  workflow_dispatch:
  
jobs:
  purge-prometheus-registry:
    runs-on: ubuntu-latest
    name: Purge Prometheus registry
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
    - uses: actions/delete-package-versions@v5
      with: 
        package-name: 'mbasri/prometheus'
        package-type: 'container'
        min-versions-to-keep: 0
        delete-only-untagged-versions: 'true'

  purge-node-exporter-registry:
      runs-on: ubuntu-latest
      name: Purge Node Exporter registry
      outputs:
        version: ${{ steps.version.outputs.version }}
      steps:
      - uses: actions/delete-package-versions@v5
        with: 
          package-name: 'mbasri/node-exporter'
          package-type: 'container'
          min-versions-to-keep: 0
          delete-only-untagged-versions: 'true'
