name: 'Purge registry'

on:
  workflow_dispatch:

env:
  REGISTRY: 'ghcr.io'
  PROMETHEUS_IMAGE_NAME: 'mbasri/prometheus'
  NODE_EXPORTER_IMAGE_NAME: 'mbasri/node-exporter'
  
jobs:
  purge-prometheus-registry:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    name: Purge Prometheus registry
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
    - uses: actions/delete-package-versions@main
      with: 
        #package-name: '${{ env.REGISTRY }}/${{ env.PROMETHEUS_IMAGE_NAME }}'
        package-name: 'prometheus'
        package-type: 'container'
        token: ${{ secrets.GITHUB_TOKEN }}
        min-versions-to-keep: 0
        delete-only-untagged-versions: 'true'

  purge-node-exporter-registry:
    runs-on: ubuntu-latest
    
    permissions:
      packages: write

    name: Purge Node Exporter registry
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
    - uses: actions/delete-package-versions@main
      with: 
        #package-name: '${{ env.REGISTRY }}/${{ env.NODE_EXPORTER_IMAGE_NAME }}'
        package-name: 'node-exporter'
        package-type: 'container'
        token: ${{ secrets.GITHUB_TOKEN }}
        min-versions-to-keep: 0
        delete-only-untagged-versions: 'true'
